package com.turborush.game.models;

/** GameState — All possible high-level game states. */
public enum GameState {
    LOADING, MAIN_MENU, GARAGE, TRACK_SELECTION, SETTINGS, PROFILE, LOGIN, RACING, PAUSED, CRASHING, GAME_OVER, LEADERBOARD, MULTIPLAYER_LOBBY, MULTIPLAYER_RACING, MULTIPLAYER_CRASHED, MULTIPLAYER_RESULTS;

    public enum WorldTheme {
        CITY, VILLAGE, MOUNTAIN, OCEAN, DESERT, SNOW, FOREST, CYBERPUNK, VOLCANO, CANYON, NEON_CITY, RETRO
    }
}
